export default class EnumTypes {
    static readonly busyStatus = 'BusyStatus';
    static readonly cartType = 'CartType';
    static readonly companyType = 'CompanyType';
    static readonly contactType = 'ContactType';
    static readonly countryCode = 'CountryCode';
    static readonly customFieldCategory = 'CustomFieldCategory';
    static readonly documentOfflineState = 'DocumentOfflineState';
    static readonly documentType = 'DocumentType';
    static readonly emailOfflineState = 'EmailOfflineState';
    static readonly globalSettingsCategory = 'GlobalSettingsCategory';
    static readonly goalType = 'GoalType';
    static readonly journalType = 'JournalType';
    static readonly knowledgeType = 'KnowledgeType';
    static readonly leadType = 'LeadType';
    static readonly marketingType = 'MarketingType';
    static readonly paymentType = 'PaymentType';
    static readonly prefixType = 'PrefixType';
    static readonly productType = 'ProductType';
    static readonly projectType = 'ProjectType';
    static readonly salaryType = 'SalaryType';
    static readonly suffixType = 'SuffixType';
    static readonly taskType = 'TaskType';
    static readonly usStatesDistrictsTerritories = 'USStatesDistrictsTerritories';
    static readonly vacationType = 'VacationType';
    static readonly workReportType = 'WorkReportType';
}