////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiRecurrencePattern extends IApiItemBase {
    TaskGuid: string | null;
    RecurrenceType: number | null;
    Interval: number | null;
    Instance: number | null;
    DayOfWeekMask: number | null;
    DayOfMonth: number | null;
    MonthOfYear: number | null;
    Regenerate: boolean | null;
    NoEndDate: boolean | null;
    Occurrences: number | null;
    PatternStartDate: string | null;
    PatternEndDate: string | null;
    EndKind: number | null;
}
