////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiXsltTransformationsModel extends IApiItemBase {
    ObjectTypeId: number | null;
    FolderName: string | null;
    TransformationGuid: string | null;
    ItemTypeGuid: string | null;
}
