////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiEmail extends IApiItemBase {
    Subject: string | null;
    SenderEmailAddress: string | null;
    SentOn: string | null;
    ReceivedTime: string | null;
    AttachmentsCount: number | null;
    To: string | null;
    Cc: string | null;
    Note: string | null;
    ImportanceEn: string | null;
    Checksum: number | null;
    MessageId: string | null;
    Hash: string | null;
    ConversationIndex: string | null;
    EmailFileExtension: string | null;
    SentMailGUID: string | null;
    IsGdprRelevant: boolean | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Leads_OutlookProjectGuid: string | null;
    Projects_OutlookProjectGuid: string | null;
    Marketing_OutlookProjectGuid: string | null;
    Tasks_TaskOriginGuid: string | null;
}
