////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBaseWithoutPrivate } from './IApiItemBase';

export interface IApiLayout extends IApiItemBaseWithoutPrivate {
    FolderName: string | null;
    IsDefault: boolean | null;
    IsSystem: boolean | null;
}
