////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiGoal extends IApiItemBase {
    TypeEn: string | null;
    Note: string | null;
    StartDate: string | null;
    EndDate: string | null;
    TurnoverGoal: number | null;
    TurnoverActual: number | null;
    TurnoverCompleted: number | null;
    ProfitGoal: number | null;
    ProfitActual: number | null;
    ProfitCompleted: number | null;
    CurrencyEn: string | null;
    TurnoverGoalDefaultCurrency: number | null;
    ProfitGoalDefaultCurrency: number | null;
    TurnoverGoalChanged: string | null;
    ProfitGoalChanged: string | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Users_GoalGuid: string | null;
}
