////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';
import { IApiEvent } from './workflowActions/IApiAction';

export interface IApiFlow extends IApiItemBase {
    ModelGuid: string | null;
    PrecedentEn: string | null;
    SuccedentEn: string | null;
    Roundtrip: boolean | null;
    AllActionEvents: IApiEvent[] | null;
}
