/////////////////////////////////////////////
//                                         //
// Do not modify this file.                //
// This file is generated by WcfGenerator. //
//                                         //
/////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiContact extends IApiItemBase {
    BusinessAddressStreet: string | null;
    BusinessAddressCity: string | null;
    BusinessAddressState: string | null;
    BusinessAddressCountryEn: string | null;
    BusinessAddressPOBox: string | null;
    BusinessAddressPostalCode: string | null;
    HomeAddressStreet: string | null;
    HomeAddressCity: string | null;
    HomeAddressState: string | null;
    HomeAddressCountryEn: string | null;
    HomeAddressPOBox: string | null;
    HomeAddressPostalCode: string | null;
    OtherAddressStreet: string | null;
    OtherAddressCity: string | null;
    OtherAddressState: string | null;
    OtherAddressCountryEn: string | null;
    OtherAddressPOBox: string | null;
    OtherAddressPostalCode: string | null;
    Company: string | null;
    Email1Address: string | null;
    Email2Address: string | null;
    Email3Address: string | null;
    FirstName: string | null;
    ICQ: string | null;
    ImportanceEn: string | null;
    LastName: string | null;
    MiddleName: string | null;
    MSN: string | null;
    Note: string | null;
    PrefixEn: string | null;
    SuffixEn: string | null;
    Skype: string | null;
    TelephoneNumber1: string | null;
    TelephoneNumber2: string | null;
    TelephoneNumber3: string | null;
    TelephoneNumber4: string | null;
    TelephoneNumber5: string | null;
    TelephoneNumber6: string | null;
    TelephoneNumber1Normalized: string | null;
    TelephoneNumber2Normalized: string | null;
    TelephoneNumber3Normalized: string | null;
    TelephoneNumber4Normalized: string | null;
    TelephoneNumber5Normalized: string | null;
    TelephoneNumber6Normalized: string | null;
    Department: string | null;
    Title: string | null;
    WebPage: string | null;
    DoNotSendNewsletter: boolean | null;
    ProfilePicture: string | null;
    ProfilePictureWidth: number | null;
    ProfilePictureHeight: number | null;
    LastActivity: string | null;
    NextStep: string | null;
    TypeEn: string | null;
    Companies_CompanyGuid: string | null;
}
