////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBaseWithoutPrivate } from './IApiItemBase';

export interface IApiLayoutsModel extends IApiItemBaseWithoutPrivate {
    FolderName: string | null;
    LayoutGuid: string | null;
    ItemTypeGuid: string | null;
    GroupGuid: string | null;
}
