////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiWorkReport extends IApiItemBase {
    Subject: string | null;
    From: string | null;
    To: string | null;
    Date: string | null;
    FromTime: string | null;
    ToTime: string | null;
    Duration: number | null;
    Note: string | null;
    Rate: number | null;
    TypeEn: string | null;
    ImportanceEn: string | null;
    DayTypeEn: string | null;
    Overtime: boolean | null;
    CalendarOrigin: string | null;
    Year: number | null;
    Month: number | null;
    CalendarEntryId: string | null;
    RateDefaultCurrency: number | null;
    RateParentCurrency: number | null;
    CurrencyEn: string | null;
    StateEn: string | null;
    PrevStateEn: string | null;
    RateAdditional: number | null;
    RateAdditionalDefaultCurrency: number | null;
    RateAdditionalParentCurrency: number | null;
    Leads_LeadGuid: string | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Users_PersonGuid: string | null;
    Tasks_TaskGuid: string | null;
    Leads_ProjectGuid: string | null;
    Projects_ProjectGuid: string | null;
}
