/////////////////////////////////////////////
//                                         //
// Do not modify this file.                //
// This file is generated by WcfGenerator. //
//                                         //
/////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiCompany extends IApiItemBase {
    AccountNumber: string | null;
    Address1POBox: string | null;
    Address1Street: string | null;
    Address1City: string | null;
    Address1State: string | null;
    Address1CountryEn: string | null;
    Address1PostalCode: string | null;
    Address2POBox: string | null;
    Address2Street: string | null;
    Address2City: string | null;
    Address2State: string | null;
    Address2CountryEn: string | null;
    Address2PostalCode: string | null;
    Address3POBox: string | null;
    Address3Street: string | null;
    Address3City: string | null;
    Address3State: string | null;
    Address3CountryEn: string | null;
    Address3PostalCode: string | null;
    CompanyName: string | null;
    Department: string | null;
    Email: string | null;
    EmployeesCount: number | null;
    Fax: string | null;
    FirstContactEn: string | null;
    ICQ: string | null;
    IdentificationNumber: string | null;
    ImportanceEn: string | null;
    LineOfBusiness: string | null;
    MailingListOther: boolean | null;
    Mobile: string | null;
    MobileNormalized: string | null;
    MSN: string | null;
    Note: string | null;
    Phone: string | null;
    PhoneNormalized: string | null;
    Purchaser: boolean | null;
    Reversal: number | null;
    Skype: string | null;
    Suppliers: boolean | null;
    VATNumber: string | null;
    WebPage: string | null;
    AdditionalDiscount: number | null;
    ID: number | null;
    Competitor: boolean | null;
    SalePriceGuid: string | null;
    NotificationByEmail: boolean | null;
    NotificationBy: string | null;
    LastActivity: string | null;
    NextStep: string | null;
    EmailOptOut: boolean | null;
    TypeEn: string | null;
}
