////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiGood extends IApiItemBase {
    Code: string | null;
    SaleCurrencyEn: string | null;
    PurchaseCurrencyEn: string | null;
    UnitEn: string | null;
    PurchasePrice: number | null;
    SalePrice: number | null;
    Note: string | null;
    Structure: string | null;
    PriceListGroupGuid: string | null;
    IsPriceSum: boolean | null;
    Description: string | null;
    InventoryQuantity: number | null;
    SalePriceDefaultCurrency: number | null;
    SalePriceChanged: string | null;
    PurchasePriceDefaultCurrency: number | null;
    PurchasePriceChanged: string | null;
    VatRate: number | null;
    VatIncluded: boolean | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    TypeEn: string | null;
    Goods_SuperiorGoodGuid: string | null;
    Margin: number | null;
    Markup: number | null;
}
