////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiCart extends IApiItemBase {
    Id: number | null;
    EffectiveFrom: string | null;
    ValidUntil: string | null;
    IsActive: boolean | null;
    TypeEn: string | null;
    PriceTotal: number | null;
    ForPayment: number | null;
    Paid: number | null;
    CurrencyEn: string | null;
    Vat: number | null;
    PriceTotalExcludingVat: number | null;
    GoodsInCartCount: number | null;
    Note: string | null;
    PriceTotalDefaultCurrency: number | null;
    PriceTotalParentCurrency: number | null;
    ForPaymentDefaultCurrency: number | null;
    ForPaymentParentCurrency: number | null;
    PaidDefaultCurrency: number | null;
    PaidParentCurrency: number | null;
    PriceTotalExcludingVatDefaultCurrency: number | null;
    PriceTotalExcludingVatParentCurrency: number | null;
    VatDefaultCurrency: number | null;
    VatParentCurrency: number | null;
    PaidChanged: string | null;
    PriceTotalChanged: string | null;
    StateEn: string | null;
    PrevStateEn: string | null;
    TaxableSupplyDate: string | null;
    AccountingCaseDate: string | null;
    PaymentDate: string | null;
    PurchaseExpenses: number | null;
    PurchaseExpensesParentCurrency: number | null;
    PurchaseExpensesDefaultCurrency: number | null;
    PurchaseExpensesChanged: string | null;
    Profit: number | null;
    ProfitDefaultCurrency: number | null;
    ProfitParentCurrency: number | null;
    ProfitChanged: string | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Contacts_ContactPersonGuid: string | null;
    Companies_CustomerGuid: string | null;
    Leads_CartGuid: string | null;
    Projects_CartGuid: string | null;
}
