////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiEnumValuesRelation extends IApiItemBase {
    EnumValueGuid: string | null;
    FieldName: string | null;
    RelatedItemGuid: string | null;
    ObjectTypeId: number | null;
    ObjectTypeFolderName: string | null;
}
