////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { type IApiItemBase } from './IApiItemBase';

export interface IApiXsltTransformation extends IApiItemBase {
    LangCode: string | null;
    Namespace: string | null;
    ObjectTypeId: number | null;
    FolderName: string | null;
    TransformationVersionEnum: number | null;
    TransformationVersion: string | null;
}
