////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiMarketingList extends IApiItemBase {
    Contact: string | null;
    Company: string | null;
    Email1Address: string | null;
    Phone: string | null;
    MarketingCampaignGuid: string | null;
    AddressStreet: string | null;
    AddressPostalCode: string | null;
    AddressCity: string | null;
    FolderName: string | null;
    FirstName: string | null;
    LastName: string | null;
    LeadGuid: string | null;
    ContactGuid: string | null;
    CompanyGuid: string | null;
}
