////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiJournal extends IApiItemBase {
    CalendarEntryID: string | null;
    Calendar_ORIGIN: string | null;
    ChangedField: string | null;
    EventEnd: string | null;
    EventStart: string | null;
    FieldValue: string | null;
    ImportanceEn: string | null;
    Note: string | null;
    PrevFieldValue: string | null;
    TypeEn: string | null;
    IsSystem: boolean | null;
    Phone: string | null;
    PhoneNormalized: string | null;
    IsGdprRelevant: boolean | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Companies_CompanyGuid: string | null;
    Contacts_ContactGuid: string | null;
    Leads_SuperiorItemGuid: string | null;
    Projects_SuperiorItemGuid: string | null;
    Marketing_MarketingGuid: string | null;
}
