////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiDocument extends IApiItemBase {
    DocName: string | null;
    Extension: string | null;
    CreationTime: string | null;
    LastWriteTime: string | null;
    DocSize: number | null;
    ImportanceEn: string | null;
    TypeEn: string | null;
    Note: string | null;
    StateEn: string | null;
    PrevStateEn: string | null;
    Preview: string | null;
    PreviewWidth: number | null;
    PreviewHeight: number | null;
    IsGdprRelevant: boolean | null;
    Companies_CompanyGuid: string | null;
    Contacts_ContactGuid: string | null;
    Leads_SuperiorItemGuid: string | null;
    Projects_SuperiorItemGuid: string | null;
    Marketing_SuperiorItemGuid: string | null;
}
