////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import type { IApiItemBase } from './IApiItemBase';

export interface IApiPayment extends IApiItemBase {
    Date: string | null;
    Paid: number | null;
    PaidDefaultCurrency: number | null;
    PaidParentCurrency: number | null;
    CurrencyEn: string | null;
    Carts_Paid_CartGuid: string | null;
}
