////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiGoodInCart extends IApiItemBase {
    Code: string | null;
    SaleCurrencyEn: string | null;
    PurchaseCurrencyEn: string | null;
    UnitEn: string | null;
    PurchasePrice: number | null;
    SalePrice: number | null;
    Quantity: number | null;
    Note: string | null;
    PriceTotal: number | null;
    Structure: string | null;
    ListPrice: number | null;
    Discount: number | null;
    HierarchyInSet: string | null;
    IsFromSet: boolean | null;
    ParentGuid: string | null;
    Rank: number | null;
    IsPriceSum: boolean | null;
    IncludeInCartPrice: boolean | null;
    ListPriceCustomized: boolean | null;
    Description: string | null;
    ChildItemsCount: number | null;
    VatRate: number | null;
    PriceTotalExcludingVat: number | null;
    VatTotal: number | null;
    SalePriceExcludingVat: number | null;
    Vat: number | null;
    PurchasePriceDefaultCurrency: number | null;
    PurchasePriceParentCurrency: number | null;
    SalePriceDefaultCurrency: number | null;
    SalePriceParentCurrency: number | null;
    PriceTotalDefaultCurrency: number | null;
    PriceTotalParentCurrency: number | null;
    ListPriceDefaultCurrency: number | null;
    ListPriceParentCurrency: number | null;
    PriceTotalExcludingVatDefaultCurrency: number | null;
    PriceTotalExcludingVatParentCurrency: number | null;
    VatTotalDefaultCurrency: number | null;
    VatTotalParentCurrency: number | null;
    SalePriceExcludingVatDefaultCurrency: number | null;
    SalePriceExcludingVatParentCurrency: number | null;
    VatDefaultCurrency: number | null;
    VatParentCurrency: number | null;
    JoinedToGuid: string | null;
    PurchasePriceChanged: string | null;
    SalePriceChanged: string | null;
    PriceTotalChanged: string | null;
    ListPriceChanged: string | null;
    PurchasePriceTotal: number | null;
    PurchasePriceTotalDefaultCurrency: number | null;
    PurchasePriceTotalParentCurrency: number | null;
    PurchasePriceTotalChanged: string | null;
    VatIncluded: boolean | null;
    Picture: string | null;
    PictureWidth: number | null;
    PictureHeight: number | null;
    Carts_GoodsInCartGuid: string | null;
    Goods_GoodsInfoGuid: string | null;
    Leads_ProjectGuid: string | null;
    Projects_ProjectGuid: string | null;
}
