////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiCurrencyExchangeRate extends IApiItemBase {
    InputCurrencyEn: string | null;
    OutputCurrencyEn: string | null;
    Rate: number | null;
    From: string | null;
    To: string | null;
    IsValid: boolean | null;
}
