////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiItemIdentifier extends IApiItemBase {
    ItemGUID: string | null;
    ItemVersion: number | null;
}
