////////////////////////////////////////////
//                                        //
// Do not modify this file.               //
// This file is generated by a generator. //
//                                        //
////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiGoodInSet extends IApiItemBase {
    ParentGUID: string | null;
    ChildGUID: string | null;
    Quantity: number | null;
    Rank: number | null;
    Price: number | null;
    IsRegular: boolean | null;
    CurrencyEn: string | null;
    IncludeInCart: boolean | null;
}
