/////////////////////////////////////////////
//                                         //
// Do not modify this file.                //
// This file is generated by WcfGenerator. //
//                                         //
/////////////////////////////////////////////

import { IApiItemBase } from './IApiItemBase';

export interface IApiLead extends IApiItemBase {
    City: string | null;
    ContactPerson: string | null;
    CurrencyEn: string | null;
    Customer: string | null;
    Email: string | null;
    EstimatedEnd: string | null;
    HID: number | null;
    LeadOriginEn: string | null;
    Note: string | null;
    Phone: string | null;
    PhoneNormalized: string | null;
    PrevStateEn: string | null;
    Price: number | null;
    PriceChanged: string | null;
    PriceDefaultCurrency: number | null;
    Probability: number | null;
    ReceiveDate: string | null;
    StateEn: string | null;
    Street: string | null;
    TypeEn: string | null;
    Zip: string | null;
    LastActivity: string | null;
    NextStep: string | null;
    EstimatedValue: number | null;
    IsCompleted: boolean | null;
    IsLost: boolean | null;
    CountryEn: string | null;
    State: string | null;
    POBox: string | null;
    EmailOptOut: boolean | null;
    Companies_CustomerGuid: string | null;
    Contacts_ContactPersonGuid: string | null;
    Marketing_MarketingGuid: string | null;
}
